# Generated by Django 4.1.3 on 2023-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_pendingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Payment Status'),
        ),
    ]
