# Generated by Django 4.1.3 on 2023-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_pendingpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='api_response',
            field=models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Payment API Response'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='order_payment_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Order ID'),
        ),
    ]
