# Generated by Django 4.1.3 on 2023-02-15 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='addPhoneNumber',
            new_name='mobileno',
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='address_name',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Others', 'Others')], default='Home', max_length=50, null=True, verbose_name='Address Name'),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='default_address',
            field=models.BooleanField(default=True, verbose_name='Default Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/20230215', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Detail'),
        ),
    ]
