# Generated by Django 4.1.3 on 2023-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_addphonenumber_useraddresses_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='default_address',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Default Address'),
        ),
    ]
