# Generated by Django 4.1.3 on 2023-02-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraddresses_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Contact Name'),
        ),
    ]
