# Generated by Django 4.1.3 on 2023-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useraddresses_addressline1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useraddresses',
            constraint=models.UniqueConstraint(condition=models.Q(('default_address', True)), fields=('user',), name='unique_primary_per_customer'),
        ),
    ]
