# Generated by Django 4.1.3 on 2023-02-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_useraddresses_addressline1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Landmark'),
        ),
    ]
