# Generated by Django 4.1.3 on 2023-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_useraddresses_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='area',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='Area'),
        ),
    ]
