# Generated by Django 4.1.3 on 2022-12-26 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(blank=True, max_length=200, null=True, verbose_name='address line 1')),
                ('addressLine2', models.CharField(blank=True, max_length=150, null=True, verbose_name='address line 2')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='select state')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='select city')),
                ('pincode', models.IntegerField(verbose_name='address pincode')),
                ('addPhoneNumber', models.CharField(blank=True, max_length=13, null=True, verbose_name='address phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user detail')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.useraddresses', verbose_name='User Addresses'),
        ),
    ]
