# Generated by Django 4.1.3 on 2022-12-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_useraddresses_alter_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresses',
            name='user',
        ),
    ]
