# Generated by Django 4.1.3 on 2023-02-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='area',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='select city'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='mobileno',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='address phone number'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='select state'),
        ),
    ]
