# Generated by Django 4.1.3 on 2022-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_customuser_address_useraddresses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/20221230', verbose_name='Avatar'),
        ),
    ]
