# Generated by Django 4.1.3 on 2022-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='item_package_quantity',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='net_content',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='packing_date',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='trending',
        ),
        migrations.AddField(
            model_name='storeproductsdetails',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Product Status'),
        ),
    ]
