# Generated by Django 4.1.3 on 2023-02-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Delivery Area')),
                ('sector', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Delivery Sector')),
                ('pincode', models.IntegerField(verbose_name='Delivery Pincode')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storedetail', verbose_name='Store Delivery Location')),
            ],
        ),
    ]
