# Generated by Django 4.1.3 on 2022-12-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='store',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='store',
            name='item_package_quantity',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Our Price'),
        ),
        migrations.AddField(
            model_name='store',
            name='max_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='store',
            name='net_content',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='packing_date',
            field=models.DateField(null=True, verbose_name='Packing Date'),
        ),
        migrations.AlterField(
            model_name='store',
            name='available_stock',
            field=models.IntegerField(default=0, verbose_name='available stock'),
        ),
    ]
