# Generated by Django 4.1.3 on 2022-12-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_products_discount_remove_products_expiry_date_and_more'),
        ('stores', '0002_store_discount_store_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(default='', max_length=50, verbose_name='Store Name')),
                ('storeAddress', models.CharField(default='', max_length=250, verbose_name='Store Address')),
                ('storeLocality', models.CharField(default='', max_length=50, verbose_name='Store Locality')),
                ('storeLocalityPinCode', models.IntegerField(max_length=6, verbose_name='Store Locality Pincode')),
                ('storeServicablePinCodes', models.CharField(default='', max_length=2048, verbose_name='Store Servicable Pincodes')),
            ],
        ),
        migrations.CreateModel(
            name='storeProductsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_retail_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='MRP')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Our Price')),
                ('net_content', models.CharField(default='', max_length=50, null=True)),
                ('item_package_quantity', models.CharField(default='', max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('packing_date', models.DateField(null=True, verbose_name='Packing Date')),
                ('available_stock', models.IntegerField(default=0, verbose_name='available stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='store product categories')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='store products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storedetail', verbose_name='Store Detail')),
            ],
        ),
        migrations.DeleteModel(
            name='store',
        ),
    ]
