# Generated by Django 4.1.3 on 2023-01-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storeproductsdetails_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductsdetails',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.storedetail', verbose_name='Store Detail'),
        ),
    ]
