# Generated by Django 4.1.3 on 2023-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_storeproductsdetails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='storePhoneNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Store Phone No.'),
        ),
    ]
