# Generated by Django 4.1.3 on 2023-01-27 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storeproductsdetails_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='storeServicablePinCodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='Store Servicable Pincodes'), blank=True, null=True, size=None),
        ),
    ]
