# Generated by Django 4.1.3 on 2023-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_storedetail_storephoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='storeRating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Store Rating'),
        ),
    ]
