# Generated by Django 4.1.3 on 2022-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storedetail_storeproductsdetails_delete_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='storeLocalityPinCode',
            field=models.IntegerField(verbose_name='Store Locality Pincode'),
        ),
    ]
