# Generated by Django 4.1.3 on 2022-12-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_storedetail_storelocalitypincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='max_retail_price',
        ),
    ]
