# Generated by Django 4.1.3 on 2023-01-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('stores', '0004_alter_storeproductsdetails_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductsdetails',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', unique=True, verbose_name='store products'),
        ),
    ]
