# Generated by Django 4.1.3 on 2023-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Message Created At'),
        ),
    ]
