# Generated by Django 4.1.3 on 2023-01-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_long_desc_products_desc_remove_products_brand_and_more'),
        ('stores', '0005_alter_storeproductsdetails_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductsdetails',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='store products'),
        ),
    ]
