# Generated by Django 4.1.3 on 2022-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storeproductsdetails_max_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedetail',
            name='storeEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Store Email ID'),
        ),
        migrations.AddField(
            model_name='storedetail',
            name='storePhoneNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Store Phone No.'),
        ),
        migrations.AddField(
            model_name='storedetail',
            name='storeRating',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='Store Rating'),
        ),
        migrations.AddField(
            model_name='storedetail',
            name='storeStatus',
            field=models.BooleanField(default=True, verbose_name='Store Status'),
        ),
        migrations.AlterField(
            model_name='storedetail',
            name='storeLocalityPinCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Store Locality Pincode'),
        ),
        migrations.AlterField(
            model_name='storedetail',
            name='storeServicablePinCodes',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='Store Servicable Pincodes'),
        ),
    ]
