# Generated by Django 4.1.3 on 2023-01-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_storeproductsdetails_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='list_price',
        ),
    ]
