# Generated by Django 4.1.3 on 2022-12-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storedetail_storeemail_storedetail_storephoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductsdetails',
            name='trending',
            field=models.BooleanField(default=False, verbose_name='Item in Trending'),
        ),
    ]
