# Generated by Django 4.1.3 on 2023-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_storeproductsdetails_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductsdetails',
            name='available_stock',
            field=models.IntegerField(default=0, verbose_name='available stock (in Nos.)'),
        ),
        migrations.AlterField(
            model_name='storeproductsdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount (in %)'),
        ),
    ]
