# Generated by Django 4.1.3 on 2023-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_storeproductsdetails_available_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductsdetails',
            name='display_home',
            field=models.BooleanField(default=False, verbose_name='Display at home'),
        ),
    ]
