# Generated by Django 4.1.3 on 2023-01-05 19:20

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Home', 'HOME'), ('Categories', 'CATEGORIES'), ('Top', 'TOP'), ('Middle', 'MIDDLE'), ('Bottom', 'BOTTOM')], max_length=255, null=True, verbose_name='Banner Position'), blank=True, null=True, size=None)),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='bannername')),
                ('banner_images', models.ImageField(upload_to='banners/20230106', verbose_name='bannerimages')),
                ('banner_status', models.CharField(choices=[('Activate', 'ACTIVATE'), ('Deactivate', 'DEACTIVATE')], default=None, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'db_table': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=None, max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/20230106', verbose_name='category image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoriesProducts',
            fields=[
                ('categoriesproduct_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'CategoriesProducts',
                'db_table': 'CategoriesProducts',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Image Id')),
                ('images', models.ImageField(upload_to='product/20230106', verbose_name='Product_Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewAndRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1024, null=True, verbose_name='Product Review')),
                ('ratings', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Product Rating')),
                ('upload_image', models.ImageField(null=True, upload_to='review/20230106', verbose_name='ImagesForReview')),
                ('review_date', models.DateTimeField(auto_now=True, verbose_name='review_date')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('long_desc', models.TextField(blank=True, max_length=5000, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('material_feature', models.CharField(blank=True, choices=[('NON VEG', 'NON VEGETERIAN'), ('VEG', 'VEGETERIAN')], max_length=50)),
                ('pro_category', products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Bread & Milk', 'BREAD & MILK'), ('Vegetables', 'VEGETABLES'), ('Breakfast & Dairy', 'BREAKFAST & DAIRY'), ('Biscuits, Snacks & Chocolates', 'BISCUITS, SNACKS & CHOCOLATES'), ('Medicines', 'MEDICINES'), ('Pan Corner', 'PAN CORNER'), ('Comida', 'COMIDA'), ('Trending', 'TRENDING')], max_length=255, null=True, verbose_name='Product Category'), blank=True, null=True, size=None)),
                ('brand', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('flavour', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('max_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='MRP')),
                ('prod_mainimage', models.ImageField(blank=True, default=None, null=True, upload_to='product/20230106', verbose_name='Product Main Image')),
                ('ingredients', models.CharField(blank=True, max_length=1050, null=True, verbose_name='Ingredients')),
                ('manufactured_by', models.CharField(blank=True, max_length=1050, null=True, verbose_name='Manufactured By')),
                ('marketed_by', models.CharField(blank=True, max_length=1050, null=True, verbose_name='Marketed By')),
                ('net_content', models.CharField(default='', max_length=50, null=True)),
                ('item_package_quantity', models.CharField(default='', max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('packing_date', models.DateField(null=True, verbose_name='Packing Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
