# Generated by Django 4.1.3 on 2023-01-23 00:28

from django.db import migrations, models
import django_quill.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Home', 'HOME'), ('Categories', 'CATEGORIES'), ('Top', 'TOP'), ('Middle', 'MIDDLE'), ('Bottom', 'BOTTOM')], max_length=255, null=True, verbose_name='Banner Position'), blank=True, null=True, size=None)),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='bannername')),
                ('banner_images', models.ImageField(upload_to='banners/20230123', verbose_name='bannerimages')),
                ('banner_status', models.CharField(choices=[('Activate', 'ACTIVATE'), ('Deactivate', 'DEACTIVATE')], default=None, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'db_table': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=None, max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/20230123', verbose_name='category image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoriesProducts',
            fields=[
                ('categoriesproduct_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'CategoriesProducts',
                'db_table': 'CategoriesProducts',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Image Id')),
                ('images', models.ImageField(upload_to='product/20230123', verbose_name='Product_Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewAndRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1024, null=True, verbose_name='Product Review')),
                ('ratings', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True, verbose_name='Product Rating')),
                ('upload_image', models.ImageField(null=True, upload_to='review/20230123', verbose_name='ImagesForReview')),
                ('review_date', models.DateTimeField(auto_now=True, verbose_name='review_date')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('desc', django_quill.fields.QuillField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('pro_category', products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Tea & Coffee', 'Tea & Coffee'), ('Fruits & Vegetables', 'Fruits & Vegetables'), ('Breakfast & Dairy', 'BREAKFAST & DAIRY'), ('Snacks & Drinks', 'Snacks & Drinks'), ('Puja Store', 'Puja Store'), ('Dry Fruits', 'Dry Fruits'), ('Trending', 'TRENDING'), ('Home & Kitchen Appliances', 'Home & Kitchen Appliances'), ('Cleaning Essentials', 'Cleaning Essentials'), ('Personal Care', 'Personal Care'), ('Cooking Essentials', 'Cooking Essentials'), ('Health & Baby Care', 'Health & Baby Care')], max_length=255, null=True, verbose_name='Product Category'), null=True, size=None)),
                ('max_retail_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='MRP (in Rs.)')),
                ('prod_mainimage', models.ImageField(blank=True, default=None, null=True, upload_to='product/20230123', verbose_name='Product Main Image')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
