# Generated by Django 4.1.3 on 2022-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='products',
            name='max_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='MRP'),
        ),
    ]
