# Generated by Django 4.1.3 on 2022-11-28 08:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_id_products_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(file_permissions_mode=420, location='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/media/product/None'), upload_to='', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_images',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(file_permissions_mode=420, location='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/media/review/<django.db.models.fields.related.ForeignKey>'), upload_to='', verbose_name=''),
        ),
    ]
