# Generated by Django 4.1.3 on 2023-01-07 12:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_long_desc_products_desc_remove_products_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='max_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='MRP'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_category',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Tea & Coffee', 'Tea & Coffee'), ('Fruits & Vegetables', 'Fruits & Vegetables'), ('Breakfast & Dairy', 'BREAKFAST & DAIRY'), ('Snacks & Drinks', 'Snacks & Drinks'), ('Puja Store', 'Puja Store'), ('Dry Fruits', 'Dry Fruits'), ('Trending', 'TRENDING'), ('Home & Kitchen Appliances', 'Home & Kitchen Appliances'), ('Cleaning Essentials', 'Cleaning Essentials'), ('Personal Care', 'Personal Care'), ('Cooking Essentials', 'Cooking Essentials'), ('Health & Baby Care', 'Health & Baby Care')], max_length=255, null=True, verbose_name='Product Category'), blank=True, null=True, size=None),
        ),
    ]
