# Generated by Django 4.1.3 on 2023-01-07 12:28

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_max_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_category',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Tea & Coffee', 'Tea & Coffee'), ('Fruits & Vegetables', 'Fruits & Vegetables'), ('Breakfast & Dairy', 'BREAKFAST & DAIRY'), ('Snacks & Drinks', 'Snacks & Drinks'), ('Puja Store', 'Puja Store'), ('Dry Fruits', 'Dry Fruits'), ('Trending', 'TRENDING'), ('Home & Kitchen Appliances', 'Home & Kitchen Appliances'), ('Cleaning Essentials', 'Cleaning Essentials'), ('Personal Care', 'Personal Care'), ('Cooking Essentials', 'Cooking Essentials'), ('Health & Baby Care', 'Health & Baby Care')], max_length=255, null=True, verbose_name='Product Category'), null=True, size=None),
        ),
    ]
