# Generated by Django 4.1.3 on 2022-11-28 08:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimages_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_url',
            field=models.CharField(default=django.core.files.storage.FileSystemStorage.url, max_length=50, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(file_permissions_mode=420, location='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/media/product/<django.db.models.fields.AutoField>'), upload_to='', verbose_name='Product Image'),
        ),
    ]
