# Generated by Django 4.1.3 on 2023-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_banners_banner_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
