# Generated by Django 4.1.3 on 2022-11-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimages_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221129', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_images',
            field=models.ImageField(upload_to='review/20221129', verbose_name='Images'),
        ),
    ]
