# Generated by Django 4.1.3 on 2023-01-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_categories_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='long_desc',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='short_desc',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/20230105', verbose_name='category image'),
        ),
    ]
