# Generated by Django 4.1.3 on 2023-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_pro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='max_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='MRP (in Rs.)'),
        ),
    ]
