# Generated by Django 4.1.3 on 2022-11-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimages_image_url_alter_productimages_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image_url',
        ),
    ]
