# Generated by Django 4.1.3 on 2022-11-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimages_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='reviews'),
        ),
    ]
