# Generated by Django 4.1.3 on 2022-11-28 16:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/product/20221128', file_permissions_mode=420, location='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/media/product/20221128'), upload_to='', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_images',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/review/20221128', file_permissions_mode=420, location='/Users/anandshekhar/Documents/GitHub/GroceriesDeliveryProject/media/review/20221128'), upload_to='', verbose_name=''),
        ),
    ]
