# Generated by Django 4.1.3 on 2023-01-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_long_desc_categories_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoriesproducts',
            options={'verbose_name_plural': 'CategoriesProducts'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bannername'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterModelTable(
            name='banners',
            table='Banners',
        ),
    ]
