# Generated by Django 4.1.3 on 2022-11-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimages_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='product_id',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='product_id',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='productreviewandratings',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='productreviewandratings',
            old_name='product_id',
            new_name='products',
        ),
    ]
