# Generated by Django 4.1.3 on 2022-11-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_id_categories_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewandratings',
            name='upload_images',
        ),
        migrations.AddField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221129', verbose_name='Images'),
        ),
    ]
