# Generated by Django 4.1.3 on 2022-11-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productreviewandratings_upload_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviewandratings',
            old_name='rating',
            new_name='ratings',
        ),
    ]
