# Generated by Django 4.1.3 on 2022-12-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_rating_productreviewandratings_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221208', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221208', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.CharField(max_length=8, verbose_name='Discount'),
        ),
    ]
