# Generated by Django 4.1.3 on 2022-12-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productimages_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productreviewandratings',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='prodimages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodImages', to='products.productimages', verbose_name='ProdImages'),
        ),
        migrations.AddField(
            model_name='products',
            name='prodreviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodReviews', to='products.productreviewandratings', verbose_name='ProdReviews'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221208', verbose_name='ImagesForReview'),
        ),
    ]
