# Generated by Django 4.1.3 on 2022-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productimages_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='list_price',
            field=models.CharField(default='', max_length=8, verbose_name='Our Price'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221209', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221209', verbose_name='ImagesForReview'),
        ),
    ]
