# Generated by Django 4.1.3 on 2022-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_list_price_alter_productimages_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Our Price'),
        ),
    ]
