# Generated by Django 4.1.3 on 2022-12-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_products_list_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodimages',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221209', verbose_name='Product Image'),
        ),
    ]
