# Generated by Django 4.1.3 on 2022-12-08 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productimages_products_alter_products_prodimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='products',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
