# Generated by Django 4.1.3 on 2022-12-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productimages_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='prodimages',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221209', verbose_name='Product Images'),
        ),
    ]
