# Generated by Django 4.1.3 on 2022-12-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimages_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(choices=[('Bread & Milk', 'BREAD & MILK'), ('Vegetables', 'VEGETABLES'), ('Breakfast & Dairy', 'BREAKFAST & DAIRY'), ('Chocolates', 'CHOCOLATES'), ('Medicines', 'MEDICINES'), ('Pan Corner', 'PAN CORNER'), ('Comida', 'COMIDA')], default=None, max_length=255),
        ),
    ]
