# Generated by Django 4.1.3 on 2022-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(choices=[('Bread & Milk', 'BREAD & MILK'), ('Vegetables', 'VEGETABLES'), ('Breakfast & Dairy', 'BREAKFAST & DAIRY'), ('Biscuits, Snacks & Chocolates', 'BISCUITS, SNACKS & CHOCOLATES'), ('Medicines', 'MEDICINES'), ('Pan Corner', 'PAN CORNER'), ('Comida', 'COMIDA'), ('Trending', 'TRENDING')], default=None, max_length=255),
        ),
    ]
