# Generated by Django 4.1.3 on 2022-12-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221210', verbose_name='Product_Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221210', verbose_name='ImagesForReview'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodimages',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221210', verbose_name='Product Images'),
        ),
    ]
