# Generated by Django 4.1.3 on 2022-12-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productimages_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviewandratings',
            name='review_date',
            field=models.DateTimeField(auto_now=True, verbose_name='review_date'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='products.products'),
        ),
    ]
