# Generated by Django 4.1.3 on 2022-12-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productreviewandratings_review_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prodimages',
        ),
        migrations.RemoveField(
            model_name='products',
            name='prodreviews',
        ),
        migrations.AddField(
            model_name='productreviewandratings',
            name='prodreviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodReviews', to='products.products', verbose_name='ProdReviews'),
        ),
        migrations.AddField(
            model_name='products',
            name='prod_mainimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221210', verbose_name='Product Main Image'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodImages', to='products.products'),
        ),
    ]
