# Generated by Django 4.1.3 on 2022-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_categories_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='position')),
                ('banner_name', models.CharField(max_length=50, verbose_name='bannername')),
                ('banner_images', models.ImageField(upload_to='banners/20221210', verbose_name='bannerimages')),
                ('banner_status', models.CharField(choices=[('Activate', 'ACTIVATE'), ('Deactivate', 'DEACTIVATE')], default=None, max_length=20)),
            ],
        ),
    ]
