# Generated by Django 4.1.3 on 2022-12-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_banners_banner_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='products',
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(upload_to='banners/20221218', verbose_name='bannerimages'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221218', verbose_name='Product_Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221218', verbose_name='ImagesForReview'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_mainimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221218', verbose_name='Product Main Image'),
        ),
        migrations.CreateModel(
            name='CategoriesProducts',
            fields=[
                ('categoriesproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Pro Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Category Products')),
            ],
            options={
                'db_table': 'CategoriesProducts',
            },
        ),
    ]
