# Generated by Django 4.1.3 on 2022-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_banners_banner_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='item_package_quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='max_retail_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='net_content',
        ),
        migrations.RemoveField(
            model_name='products',
            name='packing_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='short_desc',
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(upload_to='banners/20221224', verbose_name='bannerimages'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221224', verbose_name='Product_Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221224', verbose_name='ImagesForReview'),
        ),
        migrations.AlterField(
            model_name='products',
            name='long_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_mainimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221224', verbose_name='Product Main Image'),
        ),
    ]
