# Generated by Django 4.1.3 on 2022-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_categories_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='max_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='MRP'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(upload_to='banners/20221230', verbose_name='bannerimages'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category/20221230', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/20221230', verbose_name='Product_Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='review/20221230', verbose_name='ImagesForReview'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='flavour',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_mainimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/20221230', verbose_name='Product Main Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
