# Generated by Django 4.1.3 on 2022-12-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_products_max_retail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='products',
            name='ingredients',
            field=models.CharField(blank=True, max_length=1050, null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='products',
            name='manufactured_by',
            field=models.CharField(blank=True, max_length=1050, null=True, verbose_name='Manufactured By'),
        ),
        migrations.AddField(
            model_name='products',
            name='marketed_by',
            field=models.CharField(blank=True, max_length=1050, null=True, verbose_name='Marketed By'),
        ),
    ]
